---
  name: Build and test
  on:
     push:
        branches:
           - main
  
  jobs:
     build:
        runs-on: ubuntu-latest
        steps:
           - name: Check out repository code
             uses: actions/checkout@v2 # Expres Downgrade van v3 naar v2
  
           - name: Set up Node.js 20
             uses: actions/setup-node@v3
             with:
                node-version: "20"
  
           - name: Install dependencies
             run: yarn install
  
           - name: Lint the project
             run: yarn lint
  
           - name: Log in to Docker Hub
             uses: docker/login-action@v2
             with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
           - name: Build and push Docker image to Docker Hub
             uses: docker/build-push-action@v2
             with:
                context: .
                file: Dockerfile
                tags: robberto2003/webapp:latest
                push: true
  
           - name: Verify image build
             run: |
                docker images
  