---
name: Build and test
on:
   push:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Check out repository code
           uses: actions/checkout@v3

         - name: Set up Node.js 20
           uses: actions/setup-node@v3
           with:
              node-version: "20"

         - name: Install dependencies
           run: yarn install

         - name: Lint the project
           run: yarn lint

         - name: Build the Docker image
           uses: docker/build-push-action@v2
           with:
              context: .
              file: Dockerfile
              tags: robberto2003/webapp:latest
              push: false 

         - name: Verify image build
           run: |
              docker images
